### ISSUE TITLE
At least once delivery not implemented correctly

### ISSUE THREAD

**Issue by sfc-gh-xhuang** [deltastreaminc/flink-connector-snowflake#18]
I believe the client is flushing but I don’t see checks on offsets to confirm if the commit was successful.

**Comment by mohsenrezaeithe** [comment]
Hey @sfc-gh-xhuang, thanks for creating issues.

The writer relies on the success of the insert API currently, so using the offset tokens is a good first improvement that can be done for the sink.

Feel free to contribute the change if you're interested.
