### ISSUE TITLE
[Question] Merge Statement Support

### ISSUE THREAD

**Issue by MarquisC** [deltastreaminc/flink-connector-snowflake#23]
Sorry if I missed it, I checked through [here](https://github.com/deltastreaminc/flink-connector-snowflake/tree/main/flink-connector-snowflake/src/main/java/io/deltastream/flink/connector/snowflake/sink/internal) and saw mainly insert logic. 

Are merge statements supported and if not is that on the roadmap at all?

Thank you.

**Comment by mohsenrezaeithe** [comment]
Hey @MarquisC thanks for bringing your question here.

Currently, the connector is focused on the streaming use cases. As you probably noticed, the connector is using the Snowpipe Streaming's ingest SDK to write to Snowflake, which only support inserts.

Unfortunately, there aren't any plans to support non-streaming use cases as of this comment.
